### ISSUE TITLE
Hotspots can be moved outside image boundaries

### ISSUE THREAD

**Issue by chrjs** [summerstyle/summer#15]
Hotspots can be moved outside image boundaries (see attachment).
![hs](https://cloud.githubusercontent.com/assets/227026/16544402/81947fba-4104-11e6-83c1-3738a7cbc666.png)

**Comment by summerstyle** [comment]
Hi, chrjs.

Yes, the specification https://www.w3.org/TR/2011/WD-html5-20110525/the-map-element.html allows negative values of coords for html image maps.

**Comment by chrjs** [comment]
Thank you Vera. I see, quite surprising...
Since we don't have this requirement in our editor, we would like to have the movement blocked on the image edges. Is there any possibility to have this option implemented? How much it will cost?
Thanks.

**Comment by summerstyle** [comment]
For the editor, negative coordinates is normal, but now I am making big refactoring of the editor.
I want to divide coords library (for drawing/editing/loading/saving/exporting areas) from the editor.
Then users will can simply create many editors on one page in their projects.

This option is possible,maybe, as parameter, something like this:

``` javascript
var editor = new Editor(url, containerEl, {
    isMovableOutsideCanvas: true
});
```

But, i don't know, when it happens - I have not enough time.

You can add checking for negative coordinates in process of moving here:
https://github.com/summerstyle/summer/blob/master/summerHTMLImageMapCreator.js#L856
like this:

``` javascript
this.setCoords(Area.getMovingNormalizedCoords(this.edit('move', dx, dy))).redraw();
```

and for all types of areas static method for normalizing coords like this: 
https://github.com/summerstyle/summer/blob/master/summerHTMLImageMapCreator.js#L1388
